name: Use Bookmarklet Generator

on:
  push:
    branches:
      - main
    paths:
      - 'src/raw.js'

jobs:
  generate-bookmarklet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use Bookmarklet Generator
        uses: ulrischa/js_to_bookmarklet_action@v1
        with:
          source_js_file: 'src/raw.js'
          target_html_file: 'index.htm'
          target_element_id: 'target'
          commit_message: 'Update bookmarklet link'

